baseURL = "https://meguru-limited.github.io/prof/"
publishDir = "docs"
languageCode = "ja"
title = "About meguru_limited"
theme = "LucentLink-Hugo"
minVersion = "0.115.0"

[params]
  description     = "零細創作屋のプロフィール"
  googleAnalytics = ""    

[outputs]
  home = ["HTML"]
